### ISSUE TITLE
smaps_rollup check isn't disabled when using RSS or disabling PSS

### ISSUE THREAD

**Issue by ikirker** [JanneM/Ruse#6]
Around: <https://github.com/JanneM/Ruse/blob/cd8cba431a0285553a97fde5fac25830393f4e04/src/options.c#L185-L191>

The error message says the failure warning should be disabled if you use the `--rss` option or disable PSS at compile time, but it isn't in either case.

A quick look through the file suggests adding a check for whether `opts->pss == true` around L176-L192 might be all that's needed as a fix? Since the compile time flag sets `opts->pss` to always be false.

**Comment by JanneM** [comment]
Closed. Thanks!
